name: ${project.name}
version: ${project.version}
main: me.minoneer.bukkit.endlessdispense.EndlessDispense
author: minoneer
description: ${project.description}
api-version: '1.20.6'
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:${kotlin.version}
  - io.github.kraftlin:kraftlin-config-paper:${kraftlin.version}
  - io.github.kraftlin:kraftlin-command-paper:${kraftlin.version}
