name: ${project.name}
version: ${project.version}
main: me.minoneer.bukkit.endlessdispense.EndlessDispense
author: minoneer
description: ${project.description}
api-version: '1.20'
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:${kotlin.version}
